from django.contrib import admin
from django.urls import path, include

from hair_app import views

urlpatterns = [
    path('',views.home),
    path('login',views.login,name="login"),
    path('checkemail',views.checkemail,name="checkemail"),
    path('adminhome',views.adminhome),
    path('logincode',views.logincode),
    path('registration',views.registration),
    path('registration_post',views.registration_post),
    path('adminadd_employee',views.adminadd_employee),
    path('userhome',views.userhome),
    path('manage_emp', views.manage_emp, name='manage_emp'),
    path('add_emp', views.add_emp, name='add_emp'),
    path('add_empp', views.add_empp, name='add_empp'),
    path('manage_services', views.manage_services, name='manage_services'),
    path('edit_emp/<int:id>', views.edit_emp, name='edit_emp'),
    path('edit_empp', views.edit_empp, name='edit_empp'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('employee', views.employee),
    path('viewpro', views.viewpro),
    path('edit_emp_pro', views.edit_emp_pro),
    path('add_serv', views.add_serv),
    path('add_services', views.add_services),
    path('edit_empp1', views.edit_empp1),
    path('manage_users', views.manage_users),
    path('block_user/<id>', views.block_user),
    path('deleteservices/<id>', views.deleteservices),
    path('unblock_user/<id>', views.unblock_user),
    path('services', views.services_table),
    path('service', views.service),
    path('usrviewpro', views.usrviewpro),
    path('edit_user_profile', views.edit_user_profile),
    path('edit_profile_post', views.edit_profile_post),
    path('forgot_password', views.forgot_password),
    path('forgot_password_post', views.forgot_password_post),
    path('view_services', views.view_services),
    path('view_type/<str:type>', views.view_type, name='view_type'),  # Correct this line
    path('search_service/<str:type>', views.search_service, name='search_service'),  # Correct this line
    path('men_services', views.men_services, name='men_services'),
    path('women_services', views.women_services, name='women_services'),
    path('kids_services', views.kids_services, name='kids_services'),
    path('book_service/<int:service_id>', views.book_service, name='book_service'),
    path('add_to_cart/<id>', views.add_to_cart, name='add_to_cart'),
    path('view_cart', views.view_cart, name='view_cart'),
    path('BookNow', views.BookNow, name='BookNow'),
    path('delete_cart/<int:id>', views.delete_cart, name='delete_cart'),
    path('jquryemployee_view/<int:emid>', views.jquryemployee_view, name='jquryemployee_view'),
    path('purchase_product', views.purchase_product, name='purchase_product'),
    path('confirm_page', views.confirm_page),
    path('user_pay_proceed/<id>/<amt>', views.user_pay_proceed),
    path('on_payment_success', views.on_payment_success),
    path('view_my_bookng', views.view_my_bookng),
    path('get_timeslots_for_date', views.get_timeslots_for_date),
    path('submit_feedback', views.submit_feedback),
    path('submit_complaint', views.submit_complaint),
    path('admin_view_complaint', views.admin_view_complaint),
    path('admin_send_reply/<id>', views.admin_send_reply),
    path('admin_send_reply_post', views.admin_send_reply_post),
    path('admin_view_booking', views.admin_view_booking),
    path('searchbookingadmin', views.searchbookingadmin),
    path('admin_view_payments', views.admin_view_payments),
    path('employee_view_shedule', views.employee_view_shedule),
    path('employee_view_shedule_post', views.employee_view_shedule_post),
    path('view_cart1/<id>', views.view_cart1),
    path('purchase_product1', views.purchase_product1),
    path('confirm_page1', views.confirm_page1),
    path('user_view_reply', views.user_view_reply),
    path('bill/<id>', views.bill),



]
