# Generated by Django 5.1 on 2024-08-28 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='employee_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.FileField(upload_to='')),
                ('experience', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=50)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hair_app.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField(max_length=10)),
                ('photo', models.FileField(upload_to='')),
                ('LOGINID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hair_app.login_table')),
            ],
        ),
    ]
