# Generated by Django 5.1 on 2024-08-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='services_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='employee_table',
            name='photo',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_table',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
