# Generated by Django 5.1 on 2024-08-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair_app', '0002_services_table_employee_table_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_table',
            name='gender',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
