# Generated by Django 5.1 on 2024-08-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair_app', '0003_user_table_email_user_table_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_table',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='login_table',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
