# Generated by Django 5.1 on 2024-09-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair_app', '0004_alter_login_table_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='dob',
            field=models.DateField(default='2010-01-01'),
            preserve_default=False,
        ),
    ]
