# Generated by Django 5.1 on 2024-09-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair_app', '0005_user_table_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_table',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
