# Generated by Django 5.1 on 2024-09-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair_app', '0006_employee_table_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_table',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
