# Generated by Django 5.1 on 2024-09-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair_app', '0008_alter_employee_table_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_table',
            name='Employee_type',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
