# Generated by Django 5.1 on 2024-09-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair_app', '0009_employee_table_employee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='services_table',
            name='category',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services_table',
            name='photo',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services_table',
            name='type',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services_table',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
