# Generated by Django 5.1 on 2024-09-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair_app', '0010_services_table_category_services_table_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_table',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='services_table',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='services_table',
            name='photo',
            field=models.FileField(upload_to='services/'),
        ),
    ]
