# Generated by Django 5.1 on 2024-10-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair_app', '0011_alter_employee_table_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services_table',
            name='Duration',
            field=models.CharField(default='1 hour', max_length=30),
            preserve_default=False,
        ),
    ]
