# Generated by Django 5.1 on 2024-10-16 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair_app', '0012_services_table_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('EMPLOYEE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hair_app.employee_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hair_app.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='BookingSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('status', models.IntegerField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('MASTER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hair_app.bookingmaster')),
                ('SERVICE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hair_app.services_table')),
            ],
        ),
    ]
