# Generated by Django 5.1 on 2024-10-16 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair_app', '0013_bookingmaster_bookingsub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingsub',
            old_name='MASTER',
            new_name='BOOKING_MASTER',
        ),
        migrations.RemoveField(
            model_name='bookingmaster',
            name='EMPLOYEE',
        ),
        migrations.RemoveField(
            model_name='bookingsub',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='bookingsub',
            name='to_time',
        ),
        migrations.AlterField(
            model_name='bookingsub',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('status', models.CharField(max_length=30)),
                ('BOOKING_SUB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hair_app.bookingsub')),
                ('EMPLOYEE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hair_app.employee_table')),
            ],
        ),
    ]
