# Generated by Django 5.1 on 2024-10-25 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair_app', '0014_rename_master_bookingsub_booking_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmaster',
            name='EMPLOYEE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hair_app.employee_table'),
            preserve_default=False,
        ),
    ]
