# Generated by Django 5.1 on 2024-10-25 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair_app', '0015_bookingmaster_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='EMPLOYEE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hair_app.employee_table'),
        ),
    ]
