# Generated by Django 5.1 on 2024-10-25 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair_app', '0017_alter_bookingmaster_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hair_app.bookingmaster')),
            ],
        ),
    ]
