# Generated by Django 5.1 on 2024-10-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair_app', '0018_payment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmaster',
            name='From_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bookingmaster',
            name='To_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
