# Generated by Django 5.1 on 2024-10-29 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair_app', '0019_bookingmaster_from_time_bookingmaster_to_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('feedback', models.CharField(max_length=100)),
                ('EMPLOYEE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hair_app.employee_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hair_app.user_table')),
            ],
        ),
    ]
